# Generated by Django 2.0.5 on 2018-05-20 12:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='federal_electorate_2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elect_div', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=4)),
                ('numccds', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('projected', models.IntegerField()),
                ('total_population', models.IntegerField()),
                ('australians_over_18', models.IntegerField()),
                ('area_sqkm', models.FloatField()),
                ('sortname', models.CharField(max_length=30)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
