# Generated by Django 2.0.5 on 2018-06-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='federal_electorate_2016',
            new_name='FederalElectorate2016',
        ),
    ]
