# Generated by Django 2.0.5 on 2018-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aec', '0002_auto_20180612_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalelectorate2016',
            name='elect_div',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
