# Generated by Django 2.0.5 on 2018-06-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aec', '0002_auto_20180612_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debate_title', models.CharField(max_length=128)),
                ('debate_page_no', models.IntegerField()),
                ('subdebate1_title', models.CharField(max_length=128)),
                ('subdebate1_page_no', models.IntegerField()),
                ('subdebate2_title', models.CharField(max_length=128)),
                ('subdebate2_page_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('party', models.CharField(max_length=16)),
                ('electorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aec.FederalElectorate2016')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_talk_started', models.TimeField()),
                ('talk_type', models.CharField(max_length=32)),
                ('first_speech', models.BooleanField(default=False)),
                ('the_words', models.TextField()),
                ('debate_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansard.DebateReference')),
                ('spoken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansard.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SessionReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parliament_no', models.IntegerField()),
                ('date', models.DateField()),
                ('session_no', models.IntegerField()),
                ('period_no', models.IntegerField()),
                ('chamber', models.CharField(choices=[('House of Reps', 'House of Reps'), ('Senate', 'Senate')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='debatereference',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansard.SessionReference'),
        ),
    ]
