# Generated by Django 2.0.5 on 2018-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
