# Generated by Django 2.0.5 on 2018-06-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0003_auto_20180613_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debatereference',
            unique_together={('session', 'debate_title', 'debate_page_no', 'subdebate1_title', 'subdebate1_page_no', 'subdebate2_title', 'subdebate2_page_no')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionreference',
            unique_together={('parliament_no', 'date', 'session_no', 'period_no', 'chamber')},
        ),
    ]
