# Generated by Django 2.0.5 on 2018-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0005_auto_20180614_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatereference',
            name='subdebate1_page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debatereference',
            name='subdebate1_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debatereference',
            name='subdebate2_page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debatereference',
            name='subdebate2_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
