# Generated by Django 2.0.5 on 2018-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0007_auto_20180614_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatereference',
            name='subdebate1_title',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='debatereference',
            name='subdebate2_title',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
